#!/bin/bash
set -e -o pipefail
SCRIPT="${0##*/}"
# shellcheck disable=SC2034
SCRIPT_DIR="$(dirname "$(readlink -e "${0}")")"
# shellcheck disable=SC2064
trap "echo 'ERROR[${SCRIPT}]: Internal error' >&2" ERR

## Usage
__USAGE() {
  cat >&2 <<EOF
USAGE: ${SCRIPT} [<options>]

SYNOPSIS:
  Assymetrically encrypt (decrypt) the given data, with the given public (private) key.

OPTIONS:

  --decrypt, -d
    Decrypt data (instead of encrypt)

  --key, -k <key.pem|pkcs11:uri>
    Public key (private key); path to PEM file or PKCS#11 URI

  --input, -i <file>
    Input file (default: '-'/stdin; actual file required for decrypt)

  --output, -o <file>
    Output file (default: '-'/stdout; actual file required for encrypt)

ASYMMETRIC KEY:

  Generate with:
    read -rs PASSPHRASE; export PASSPHRASE
    openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 \
    | openssl pkcs8 -topk8 -iter 100000 -passout env:PASSPHRASE -out key.pem
    openssl pkey -passin env:PASSPHRASE -in key.pem -pubout > pub.pem

EOF
}

# Arguments
DECRYPT=
AKEY=
INPUT='-'
OUTPUT='-'
__OPTION() {
  [ -z "${2}" ] && echo "ERROR[${SCRIPT}]: Missing option parameter (${1})" >&2 && exit 1
  return 0
}
while [ -n "${1}" ]; do
  case "${1}" in
    '-h'|'--help'|'help') __USAGE && exit 1;;
    '--decrypt'|'-d') DECRYPT='yes';;
    '--key'|'-k') __OPTION "${@}"; AKEY="${2}"; shift;;
    '--input'|'-i') __OPTION "${@}"; INPUT="${2}"; shift;;
    '--output'|'-o') __OPTION "${@}"; OUTPUT="${2}"; shift;;
    -*) echo "ERROR[${SCRIPT}]: Invalid option (${1})" >&2 && exit 1;;
    *) echo "WARNING[${SCRIPT}]: invalid argument (${1})" >&2
  esac
  shift
done

## Checks

# Asymmetric key (PEM file)
if [ -z "${AKEY}" ] || { [ "${AKEY:0:7}" != 'pkcs11:' ] && [ ! -r "${AKEY}" ]; }; then
  echo "ERROR[${SCRIPT}]: Invalid/unreadable key (PEM) file (${AKEY:-n/a})" >&2 && exit 1
fi
if [ -z "${DECRYPT}" ]; then
  if [ "${OUTPUT}" == '-' ]; then
    echo "ERROR[${SCRIPT}]: Output (--output) must be an actual file (name)" >&2 && exit 1
  fi
  OUTPUT_DIR="$(dirname "${OUTPUT}")"
  if [ ! -d "${OUTPUT_DIR}" ] || [ ! -w "${OUTPUT_DIR}" ]; then
    echo "ERROR[${SCRIPT}]: Invalid/unwritable output directory (${OUTPUT_DIR})" >&2 && exit 1
  fi
else
  if [ "${INPUT}" == '-' ]; then
    echo "ERROR[${SCRIPT}]: Input (--input) must be an actual file (name)" >&2 && exit 1
  fi
  if [ ! -r "${INPUT}" ]; then
    echo "ERROR[${SCRIPT}]: Invalid/unreadable data (${INPUT})" >&2 && exit 1
  fi
  if [ ! -r "${INPUT}.key" ]; then
    echo "ERROR[${SCRIPT}]: Invalid/unreadable data key (${INPUT}.key)" >&2 && exit 1
  fi
fi

## Helper
__openssl_pkcs11_conf() {
  cat <<EOF >"${1}"
## REF: https://github.com/cedric-dufour/scriptisms/blob/master/system/openssl.opensc-pkcs11.conf
openssl_conf = SSL_Configuration
[ SSL_Configuration ]
providers = SSL_Providers
[ SSL_Providers ]
default = PROV_default
pkcs11 = PROV_pkcs11
[ PROV_default ]
activate = 1
[ PROV_pkcs11 ]
module = /usr/lib/x86_64-linux-gnu/ossl-modules/pkcs11.so
pkcs11-module-path = /usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so
activate = 1
EOF

}

## Main

# Symmetric key
if [ "${AKEY:0:7}" == 'pkcs11:' ]; then
  OPENSSL_CONF="$(mktemp --suffix .openssl.conf)"
  # shellcheck disable=SC2064
  trap "rm -rf '${OPENSSL_CONF}'" EXIT
  __openssl_pkcs11_conf "${OPENSSL_CONF}"
  export OPENSSL_CONF
fi
if [ -z "${DECRYPT}" ]; then
  if [ "${AKEY:0:7}" == 'pkcs11:' ]; then
    [[ "${AKEY}" =~ 'type=' ]] || AKEY="${AKEY};type=public"
  fi
  SKEY="$(openssl rand -base64 24)"
  echo "${SKEY}" | openssl pkeyutl -encrypt -pubin -inkey "${AKEY}" | base64 \
  > "${OUTPUT}.key"
  export SKEY
else
  if [ "${AKEY:0:7}" == 'pkcs11:' ]; then
    [[ "${AKEY}" =~ 'type=' ]] || AKEY="${AKEY};type=private"
  fi
  SKEY="$(base64 -d "${INPUT}.key" | openssl pkeyutl -decrypt -inkey "${AKEY}")"
  export SKEY
fi

# Encryption/decryption
if [ -z "${DECRYPT}" ]; then
  cat "${INPUT}" | openssl enc -aes-256-ctr -e -pbkdf2 -iter 100000 -pass env:SKEY -out "${OUTPUT}"
  sha256sum "${OUTPUT}" | sed 's| .*/| |' > "${OUTPUT}.sha256sum"
else
  openssl enc -aes-256-ctr -d -pbkdf2 -iter 100000 -pass env:SKEY -in "${INPUT}" | cat "${OUTPUT}"
fi

## Done
exit 0
