## OpenSSL Configuration for OpenSC PKCS#11 integration
## REF: https://docs.openssl.org/master/man5/config/

## Initialization
openssl_conf = SSL_Configuration

[ SSL_Configuration ]
providers = SSL_Providers


## Providers
[ SSL_Providers ]
default = PROV_default
pkcs11 = PROV_pkcs11

# Default
[ PROV_default ]
activate = 1

# PKCS#11
# REF: https://github.com/openssl-projects/pkcs11-provider
# DEPs: apt-get install pcscd opensc opensc-pkcs11 pkcs11-provider
[ PROV_pkcs11 ]
module = /usr/lib/x86_64-linux-gnu/ossl-modules/pkcs11.so
pkcs11-module-path = /usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so
activate = 1
