#!/bin/bash
# shellcheck disable=SC2034
set -e -o pipefail
SCRIPT="${0##*/}"
SCRIPT_DIR="$(dirname "$(realpath -e "${0}")")"

## Defaults
: "${DOWNLOAD_INSTALL_BIN_DIR:=${HOME}/bin}"
: "${DOWNLOAD_INSTALL_LINK_DIR:=${HOME}/bin}"


## Usage
__USAGE() {
  cat <<EOF
USAGE: "${SCRIPT} <version>

SYNOPSIS:
  Download and install (symlink) the given Kubectl version from
    https://github.com/kubernetes/kubernetes/releases/
EOF
}
{ [ $# -lt 1 ] || [ "${1##*-}" == 'help' ]; } && __USAGE && exit 1

# Arguments
VERSION="${1}"


## Parameters
DOWNLOAD_URL="https://dl.k8s.io/v${VERSION}/kubernetes-client-linux-amd64.tar.gz"
DOWNLOAD_INSTALL_BIN="${DOWNLOAD_INSTALL_BIN_DIR}/kubectl-${VERSION}"
DOWNLOAD_INSTALL_LINK="${DOWNLOAD_INSTALL_LINK_DIR}/kubectl"


## Download
DOWNLOAD_TMP="$(mktemp --suffix=.tar.gz)"
# shellcheck disable=SC2064
trap "rm -f '${DOWNLOAD_TMP}'" EXIT

echo "INFO[${SCRIPT}]: Downloading ${DOWNLOAD_URL} ..."
wget -q -O "${DOWNLOAD_TMP}" "${DOWNLOAD_URL}"

echo "INFO[${SCRIPT}]: Installing ${DOWNLOAD_INSTALL_LINK} -> ${DOWNLOAD_INSTALL_BIN} ..."
tar -O -xaf "${DOWNLOAD_TMP}" kubernetes/client/bin/kubectl > "${DOWNLOAD_INSTALL_BIN}"
chmod a+rx "${DOWNLOAD_INSTALL_BIN}"
rm -f "${DOWNLOAD_INSTALL_LINK}"
ln -rs "${DOWNLOAD_INSTALL_BIN}" "${DOWNLOAD_INSTALL_LINK}"

echo "INFO[${SCRIPT}]: Done!"
kubectl version --client=true --short=true | head -n 1
