#!/bin/bash
set -e -o pipefail
SCRIPT="${0##*/}"
SCRIPT_DIR="$(dirname "$(realpath -e "${0}")")"

## Defaults
: "${DOWNLOAD_INSTALL_BIN_DIR:=${HOME}/bin}"
: "${DOWNLOAD_INSTALL_LINK_DIR:=${HOME}/bin}"


## Usage
__USAGE() {
  cat <<EOF
USAGE: "${SCRIPT} <version> <version:ocaml>

SYNOPSIS:
  Download and install (symlink) the given Unison version from
    https://github.com/bcpierce00/unison/releases
EOF
}
[ $# -lt 2 -o "${1##*-}" == 'help' ] && __USAGE && exit 1

# Arguments
VERSION="${1}"
VERSION_OCAML="${2}"


## Parameters
DOWNLOAD_URL="https://github.com/bcpierce00/unison/releases/download/v${VERSION}/unison-v${VERSION}+ocaml-${VERSION_OCAML}+x86_64.linux.tar.gz"
DOWNLOAD_INSTALL_BIN="${DOWNLOAD_INSTALL_BIN_DIR}/unison-${VERSION}"
DOWNLOAD_INSTALL_LINK="${DOWNLOAD_INSTALL_LINK_DIR}/unison"


## Download
DOWNLOAD_TMP="$(mktemp --suffix=.tar.gz)"
trap "rm -f '${DOWNLOAD_TMP}'" EXIT

echo "INFO[${SCRIPT}]: Downloading ${DOWNLOAD_URL} ..."
wget -q -O "${DOWNLOAD_TMP}" "${DOWNLOAD_URL}"

echo "INFO[${SCRIPT}]: Installing ${DOWNLOAD_INSTALL_LINK} -> ${DOWNLOAD_INSTALL_BIN} ..."
tar -O -xaf "${DOWNLOAD_TMP}" bin/unison > "${DOWNLOAD_INSTALL_BIN}"
chmod a+rx "${DOWNLOAD_INSTALL_BIN}"
rm -f "${DOWNLOAD_INSTALL_LINK}"
ln -rs "${DOWNLOAD_INSTALL_BIN}" "${DOWNLOAD_INSTALL_LINK}"

echo "INFO[${SCRIPT}]: Done!"
unison -version | head -n 1
