#!/bin/bash
set -e -o pipefail
SCRIPT="${0##*/}"
SCRIPT_DIR="$(dirname "$(realpath -e "${0}")")"

## Defaults
: "${DOWNLOAD_INSTALL_BIN_DIR:=${HOME}/bin}"
: "${DOWNLOAD_INSTALL_LINK_DIR:=${HOME}/bin}"


## Usage
__USAGE() {
  cat <<EOF
USAGE: "${SCRIPT} <version>

SYNOPSIS:
  Download and install (symlink) the given (Go-)Jsonnet version from
    https://github.com/google/go-jsonnet/releases/...
EOF
}
[ $# -lt 1 -o "${1##*-}" == 'help' ] && __USAGE && exit 1

# Arguments
VERSION="${1}"


## Parameters
DOWNLOAD_URL="https://github.com/google/go-jsonnet/releases/download/v${VERSION}/go-jsonnet_${VERSION}_Linux_x86_64.tar.gz"
DOWNLOAD_INSTALL_BIN="${DOWNLOAD_INSTALL_BIN_DIR}/jsonnet-${VERSION}"
DOWNLOAD_INSTALL_LINK="${DOWNLOAD_INSTALL_LINK_DIR}/jsonnet"


## Download
DOWNLOAD_TMP="$(mktemp --suffix=.tar.gz)"
trap "rm -f '${DOWNLOAD_TMP}'" EXIT

echo "INFO[${SCRIPT}]: Downloading ${DOWNLOAD_URL} ..."
wget -q -O "${DOWNLOAD_TMP}" "${DOWNLOAD_URL}"

echo "INFO[${SCRIPT}]: Installing ${DOWNLOAD_INSTALL_LINK} -> ${DOWNLOAD_INSTALL_BIN} ..."
tar -O -xaf "${DOWNLOAD_TMP}" jsonnet > "${DOWNLOAD_INSTALL_BIN}"
chmod a+rx "${DOWNLOAD_INSTALL_BIN}"
rm -f "${DOWNLOAD_INSTALL_LINK}"
ln -rs "${DOWNLOAD_INSTALL_BIN}" "${DOWNLOAD_INSTALL_LINK}"

echo "INFO[${SCRIPT}]: Done!"
jsonnet -version | head -n 1
